version : '3.3'
services:
  mysqldatabase:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
  saifkadri:
    image :saifkadri/examen-rattrapage-1.0
  
  
